create table if not exists public.sudoku_completions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  puzzle_id text not null check (puzzle_id ~ '^[FMDX]-[0-9]+$'),
  difficulty text not null check (difficulty in ('easy', 'medium', 'hard', 'expert')),
  seed integer not null check (seed >= 0),
  raw_time_seconds integer not null check (raw_time_seconds >= 0),
  penalties_seconds integer not null default 0 check (penalties_seconds >= 0),
  final_time_seconds integer not null check (final_time_seconds = raw_time_seconds + penalties_seconds),
  errors integer not null default 0 check (errors >= 0),
  notes_used boolean not null default false,
  highlight_same boolean not null default true,
  check_errors boolean not null default true,
  completed_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists sudoku_completions_user_completed_at_idx
  on public.sudoku_completions (user_id, completed_at desc);

create index if not exists sudoku_completions_puzzle_final_time_idx
  on public.sudoku_completions (puzzle_id, final_time_seconds);

alter table public.sudoku_completions enable row level security;

create policy "Users can read their own Sudoku completions"
  on public.sudoku_completions
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

create policy "Users can create their own Sudoku completions"
  on public.sudoku_completions
  for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

create policy "Users can delete their own Sudoku completions"
  on public.sudoku_completions
  for delete
  to authenticated
  using ((select auth.uid()) = user_id);
