create table if not exists public.sudoku_public_scores (
  id bigint generated by default as identity primary key,
  visitor_id uuid not null,
  user_id uuid references auth.users(id) on delete set null,
  nickname text not null check (char_length(btrim(nickname)) between 2 and 24),
  puzzle_id text not null check (puzzle_id ~ '^[FMDX]-[0-9]+$'),
  difficulty text not null check (difficulty in ('easy', 'medium', 'hard', 'expert')),
  seed integer not null check (seed >= 0),
  raw_time_seconds integer not null check (raw_time_seconds >= 0),
  penalties_seconds integer not null default 0 check (penalties_seconds >= 0),
  final_time_seconds integer not null check (final_time_seconds = raw_time_seconds + penalties_seconds),
  errors integer not null default 0 check (errors >= 0),
  notes_used boolean not null default false,
  highlight_same boolean not null default true,
  check_errors boolean not null default true,
  completed_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists sudoku_public_scores_visitor_puzzle_unique_idx
  on public.sudoku_public_scores (visitor_id, puzzle_id);

create unique index if not exists sudoku_public_scores_user_puzzle_unique_idx
  on public.sudoku_public_scores (user_id, puzzle_id)
  where user_id is not null;

create index if not exists sudoku_public_scores_puzzle_final_time_idx
  on public.sudoku_public_scores (puzzle_id, final_time_seconds, completed_at);

alter table public.sudoku_public_scores enable row level security;

create policy "Anyone can submit a public Sudoku score"
  on public.sudoku_public_scores
  for insert
  to anon, authenticated
  with check (
    char_length(btrim(nickname)) between 2 and 24
    and (user_id is null or (select auth.uid()) = user_id)
  );

revoke all on table public.sudoku_public_scores from anon, authenticated;
grant insert on table public.sudoku_public_scores to anon, authenticated;
grant usage, select on sequence public.sudoku_public_scores_id_seq to anon, authenticated;

drop view if exists public.sudoku_leaderboard;

create view public.sudoku_leaderboard as
select
  puzzle_id,
  difficulty,
  nickname,
  final_time_seconds,
  errors,
  notes_used,
  highlight_same,
  check_errors,
  completed_at
from public.sudoku_public_scores;

grant select on public.sudoku_leaderboard to anon, authenticated;
